### ISSUE TITLE
Expose functionnalities to python

### ISSUE THREAD

**Issue by arita37** [foolnotion/operon#3]
Is there any plan to expose some API to python 
using SWIG or PyBinGen ?

PYGMO is a project which has similar architecture than you, so it can done 
relatively easily.

**Comment by foolnotion** [comment]
Yes, there are Python bindings that are already functional, although still a work in progress. Just have a look in the examples folder.
The bindings are created using `pybind11` and allow a great deal of flexibility in the way you can mix and match C++ and python to achieve your goals.
